[phases.setup]
nixPkgs = [
  "chromium",
  "playwright-driver",
  "gobject-introspection",
  "glib",
  "nss",
  "nspr",
  "atk",
  "cups",
  "dbus",
  "libdrm",
  "libxkbcommon",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "mesa",
  "expat",
  "pango",
  "cairo",
  "alsa-lib",
]

[phases.install]
cmds = ["pip install -r requirements.txt", "playwright install chromium"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
